title: devVinish.com
description: "Vinish Kapoor's page on GitHub"
author:
  name: "VinishKapoor"
  email: "vin@vin.com"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Vinish"
year : "2019"
